import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Security",
  description: "Generated by create next app",
};

export default function PageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        {children}
      </body>
    </html>
  );
}
